# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomlyze < Formula
  desc "A fast, reliable SBOM diff and analysis tool"
  homepage "https://github.com/rezmoss/sbomlyze"
  version "0.3.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rezmoss/sbomlyze/releases/download/v0.3.2/sbomlyze_0.3.2_Darwin_x86_64.tar.gz"
      sha256 "34c5d7374c3a4fa319c54fa90a2362273bb7ef7406b8476b2bf8c01008df5e05"

      define_method(:install) do
        bin.install "sbomlyze"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rezmoss/sbomlyze/releases/download/v0.3.2/sbomlyze_0.3.2_Darwin_arm64.tar.gz"
      sha256 "c7bde33d3fc341e16949b35bec10eeb4f0932d9e0d141ad055d75c1cc1d98e68"

      define_method(:install) do
        bin.install "sbomlyze"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rezmoss/sbomlyze/releases/download/v0.3.2/sbomlyze_0.3.2_Linux_x86_64.tar.gz"
      sha256 "4c592cad8e3fb6a03f8c946fece267b243f48361d9c6d8a4dde04de0ac7e2f84"
      define_method(:install) do
        bin.install "sbomlyze"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rezmoss/sbomlyze/releases/download/v0.3.2/sbomlyze_0.3.2_Linux_armv6.tar.gz"
      sha256 "a6deb5497c87141ee081ba6683db09c72be264eb29ef8887eaa888b3d5679ab7"
      define_method(:install) do
        bin.install "sbomlyze"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rezmoss/sbomlyze/releases/download/v0.3.2/sbomlyze_0.3.2_Linux_arm64.tar.gz"
      sha256 "360e1ec33543e01c143e780361d5112a804a8c265c9f79f2e737485eb23cbe80"
      define_method(:install) do
        bin.install "sbomlyze"
      end
    end
  end

  test do
    system "#{bin}/sbomlyze", "--version"
  end
end
