# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomlyze < Formula
  desc "A fast, reliable SBOM diff and analysis tool"
  homepage "https://github.com/rezmoss/sbomlyze"
  version "0.3.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rezmoss/sbomlyze/releases/download/v0.3.5/sbomlyze_0.3.5_Darwin_x86_64.tar.gz"
      sha256 "9a5d0ccb28ad9479cc60ff2c7e7bc7834fb965ef2ffaf643610ee825e0f08afd"

      define_method(:install) do
        bin.install "sbomlyze"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rezmoss/sbomlyze/releases/download/v0.3.5/sbomlyze_0.3.5_Darwin_arm64.tar.gz"
      sha256 "48de503da865f9ed3de5229794c240a8e7eff32ecf1dafebe7e6c15a03ab7f8d"

      define_method(:install) do
        bin.install "sbomlyze"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rezmoss/sbomlyze/releases/download/v0.3.5/sbomlyze_0.3.5_Linux_x86_64.tar.gz"
      sha256 "6f39898ef9787f58086b9619e28042a309545b73966cef3c7a4e2f04962dd123"
      define_method(:install) do
        bin.install "sbomlyze"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rezmoss/sbomlyze/releases/download/v0.3.5/sbomlyze_0.3.5_Linux_armv6.tar.gz"
      sha256 "8355cede737e738c929f69d676925a8b6e064bafd64dfbe3ed5327ed82fda395"
      define_method(:install) do
        bin.install "sbomlyze"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rezmoss/sbomlyze/releases/download/v0.3.5/sbomlyze_0.3.5_Linux_arm64.tar.gz"
      sha256 "39c18af1d971ae7a62301a4ec74e5afa5bde050f86e8d04fe5a51649350b8547"
      define_method(:install) do
        bin.install "sbomlyze"
      end
    end
  end

  test do
    system "#{bin}/sbomlyze", "--version"
  end
end
