# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomlyze < Formula
  desc "A fast, reliable SBOM diff and analysis tool"
  homepage "https://github.com/rezmoss/sbomlyze"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rezmoss/sbomlyze/releases/download/v0.5.0/sbomlyze_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "13b6df12ac657a6cd79c2b8cc68284a0acea03cf071647b3eb5a9d4e8ff716b4"

      define_method(:install) do
        bin.install "sbomlyze"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rezmoss/sbomlyze/releases/download/v0.5.0/sbomlyze_0.5.0_Darwin_arm64.tar.gz"
      sha256 "507b1a19eaf55184cd59410eda6e2d7343b9fa380c78de7666df1a0ebc9c3376"

      define_method(:install) do
        bin.install "sbomlyze"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rezmoss/sbomlyze/releases/download/v0.5.0/sbomlyze_0.5.0_Linux_x86_64.tar.gz"
      sha256 "1cbd4c67a750da663877111d50164850c330fefa156b2e94a871888f2ef934c0"
      define_method(:install) do
        bin.install "sbomlyze"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rezmoss/sbomlyze/releases/download/v0.5.0/sbomlyze_0.5.0_Linux_armv6.tar.gz"
      sha256 "c1c53e321daff296b282b51914a6f92ec9e958bb37e5a974327c5e8a38cdd42c"
      define_method(:install) do
        bin.install "sbomlyze"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rezmoss/sbomlyze/releases/download/v0.5.0/sbomlyze_0.5.0_Linux_arm64.tar.gz"
      sha256 "f08234459a9864a5e4a761a5244bf5c8940f2606318ba858125789efe30d9c6c"
      define_method(:install) do
        bin.install "sbomlyze"
      end
    end
  end

  test do
    system "#{bin}/sbomlyze", "--version"
  end
end
